tools:
    bcftools: /Varpipe/bcftools/bcftools
    bedtools: /Varpipe/bedtools
    vcfannotate: /Varpipe/vcftools/bin/vcf-annotate
    bwa: /Varpipe/bwa
    samtools: /Varpipe/samtools
    qualimap: /Varpipe/qualimap_v2.1.1/qualimap
    pigz: /Varpipe/pigz
    unpigz: /Varpipe/unpigz
    fastqc: /Varpipe/FastQC/fastqc
    picard: /Varpipe/picard/picard.jar
    trimmomatic: /Varpipe/trimmomatic-0.36.jar
    gatk: /Varpipe/GenomeAnalysisTK.jar
    vcftools: /Varpipe/vcftools/bin/vcftools
    vcfutils: /Varpipe/bcftools/vcfutils.pl 
    annotator: /Varpipe/snpEff/snpEff.jar
scripts:
    parser: /Varpipe/parse_annotation.py
    lineage_parser: /Varpipe/lineage_parser.py
    vcf_parser: /Varpipe/raw_vcf_parse.py
    lineages: /Varpipe/lineage_markers.txt
    excluded: /Varpipe/excluded_loci.txt
    coverage_estimator: /Varpipe/coverage_estimator.py
    bedlist_one: /Varpipe/bed_1.txt
    bedlist_two: /Varpipe/bed_2.txt
    bedlist_merge: /Varpipe/bed_merge.txt     
    resis_parser: /Varpipe/resis_parser.py
    mutationloci: /Varpipe/mutation_loci.txt
    snplist: /Varpipe/snps.vcf
    merger: /Varpipe/merge_vcfs.py     
other:
    threads: '8'
