tools:
    bcftools: /Varpipe/bin/bcftools/bcftools
    bedtools: /Varpipe/bin/bedtools
    vcfannotate: /Varpipe/bin/vcftools/bin/vcf-annotate
    fastqvalidator: /Varpipe/bin/fastQValidator
    bwa: /Varpipe/bin/bwa
    samtools: /Varpipe/bin/samtools/samtools
    qualimap: /Varpipe/bin/qualimap/qualimap
    pigz: /Varpipe/bin/pigz
    unpigz: /Varpipe/bin/unpigz
    prinseq: /Varpipe/bin/prinseq-lite.pl
    fastqc: /Varpipe/bin/FastQC/fastqc
    picard: /Varpipe/bin/picard/picard.jar
    gatk: /Varpipe/bin/GenomeAnalysisTK.jar
    vcftools: /Varpipe/bin/vcftools/bin/vcftools
    vcfutils: /Varpipe/bin/bcftools/vcfutils.pl 
    annotator: /Varpipe/bin/snpEff/snpEff.jar
        
directories:
    kraken: /KRAKEN/kraken
    krakendb: /KRAKEN/customdb
    krakenreport: /KRAKEN/kraken-report

scripts:
    parser: /Varpipe/bin/parse_annotation.py
    lineage_parser: /Varpipe/bin/lineage_parser.py
    vcf_parser: /scicomp/home/krt7/binary/raw_vcf_parse.py
    lineages: /Varpipe/bin/lineage_markers.txt
    excluded: /Varpipe/bin/excluded_loci.txt
    coverage_estimator: /Varpipe/bin/coverage_estimator.py
    resloci: /Varpipe/bin/included_loci.txt
    bedlist: /Varpipe/bin/bed_list.txt     
    resis_parser: /Varpipe/bin/resis_parser.py
    del_parser: /Varpipe/bin/del_parse.py
    mutationloci: /Varpipe/bin/mutation_loci.txt
    snplist: /Varpipe/bin/snps.vcf
other:
    threads: '12'
